---
title: "MATH167R: Overview"
author: "Peter Gao"
format: 
  revealjs:
    theme: [./slides.scss, ../theme.scss]
editor: visual
---

## Course information

+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Instructor**   | Peter Gao                                                                                                                                                                               |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Office**       | MH 311                                                                                                                                                                                  |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Lectures**     | Weekly on Monday and Wednesday                                                                                                                                                          |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Office Hours** | Monday and Wednesday, 1:30-2:30pm                                                                                                                                                       |
|                  |                                                                                                                                                                                         |
|                  | or email for an appointment                                                                                                                                                             |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Email**        | peter.gao \[at sjsu\]                                                                                                                                                                   |
|                  |                                                                                                                                                                                         |
|                  | *I will make every effort to respond to emails within a day, but please feel free to send me a reminder after 48 hours have passed. Please include \[MATH 167R\] in your subject line.* |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Where to look

**Course website**: Course slides, assignment instructions, data.

**Canvas**: Submitting assignments, receiving grades.

## What you need

Access to a computer...

## Course structure

Your final grade will be calculated as follows:

-   15%: Check-ins

-   30%: Labs

-   15%: Midterm exam

-   20%: Final exam

-   20%: Class project

## Assignments

-   **Check-ins**: On most Mondays, you will be assigned short check-in assignments. These are designed to be completed during lab or shortly after and will be due at the start of the next class. At the end of the quarter, your lowest check-in grade will be dropped. They will be graded on the following two point scale:

    -   0: indicates incomplete or unacceptable work

    -   1: represents demonstrated effort towards completing at least 75% of the assignment

    -   2: represents demonstrated effort towards completing the entire assignment.

## Assignments

-   **Labs**: On most Wednesdays, you will be assigned Labs. These are extended, more complicated assignments that you will likely not be able to complete during class. They will typically be due the next Wednesday.

## Assignments

-   **Midterm and Final Exams**: There will be one in-person midterm during the semester and one final exam during finals week. Practice questions will be provided in advance of the exams.

-   **Class Project**: During the semester, you will complete a class project that requires you to apply the data manipulation, visualization, and analysis skills covered in this course to a real-world dataset of your choice.

## Expectations

-   **Late Work**: In general, the late policy is as follows: Any assignment that is received late but less than 24 hours late will receive a grade penalty of 25%. Any assignment that is received 24--48 hours late will receive a grade penalty of 50%. Assignments will not be accepted more than 48 hours late.

## Expectations

-   **Late Work**: In general, the late policy is as follows: Any assignment that is received late but less than 24 hours late will receive a grade penalty of 25%. Any assignment that is received 24--48 hours late will receive a grade penalty of 50%. Assignments will not be accepted more than 48 hours late.

## Collaboration

On most assignments, collaboration is allowed and encouraged. You may discuss problems, approaches, and solutions with your classmates. Acceptable collaboration is limited to your classmates in this course and you must clearly include on any collaborative work the name(s) of anyone with whom you worked. Additionally, all submitted work must be your own; you should not submit code or answers copied from any resource including your classmates. Plagiarism and cheating is easy to detect and can lead to serious negative consequences for you. If you have any questions regarding this policy, please ask for clarification.

## ChatGPT (and other tools)...

Students are encouraged to use online resources including large language model-based chatbots (ex. ChatGPT) **as aids for learning and understanding course material**. However, the use of external resources like ChatGPT to generate code or answers for course assignments, exams, and projects is not permitted.

## Discussion

You are encouraged to participate on the Canvas discussion forum by posting questions about assignments and answering questions from other students. Posts may not include substantial amounts of code that can be used for a solution to any problem, but may include code snippets within reason. Participation, in the form of both questions and answers, can earn you up to 2% extra credit for your final grade. Posts will be evaluated based on how substantive and helpful they are to the class.

## Office Hours

Please come

## Slides explained

Slides will be posted on the course website before class.

## What is R?

{{< kbd Shift-Ctrl-P >}}

## Why R?

## Goals

## R: A fancy calculator

## More than a fancy calculator

## Data analysis

## Visualization

## Communication

## Installing R

## Your first check-in

## Running your first R code

## Creating your first R Markdown report
